### ISSUE TITLE
Adding Hello World in Scala

### ISSUE THREAD

**Issue by RAGHAVS1304** [handikatriarlan/hello-world-in-every-language#13]
Adding the Scala code for Hello World.

**Comment by RAGHAVS1304** [comment]
@handikatriarlan please assign it to me under Hacktoberfest 2024

**Comment by handikatriarlan** [comment]
I didn't see your PR. Please submit a PR to this repository first

**Comment by handikatriarlan** [comment]
oops, sorry, i missed it. okay i'll merge it
