### ISSUE TITLE
Adding helloworld in Bash.

### ISSUE THREAD

**Issue by Prem-Kumar-Dev** [handikatriarlan/hello-world-in-every-language#28]
Adding helloworld in Bash.

**Comment by handikatriarlan** [comment]
Bash has been created before, please create hello world in another language or you can add numeric at the end of the file, for example: hello_world_2.sh

**Comment by Prem-Kumar-Dev** [comment]
@updated PR, kindly review and provide hacktoberfest2024-accepted label
