### ISSUE TITLE
Adding Hello Word in Erlang

### ISSUE THREAD

**Issue by RAGHAVS1304** [handikatriarlan/hello-world-in-every-language#3]
Adding the erlang code for Hello World.

**Comment by RAGHAVS1304** [comment]
@handikatriarlan please assign this issue to me under Hacktoberfest 2024.
Thanks

**Comment by handikatriarlan** [comment]
Aight, thanks for your contribution.

**Comment by RAGHAVS1304** [comment]
Hey can the same user add it in different languages i.e. can i add it in more languages, if it is fine to do so?
