### ISSUE TITLE
Feature Request: Add "Hello World" in Golang

### ISSUE THREAD

**Issue by aswathcm29** [handikatriarlan/hello-world-in-every-language#5]
## Description

This issue is to add a simple "Hello World" program using Golang to the repository. This addition can serve as a basic example for beginners or as a starting point for Golang-related contributions.

## Steps to Reproduce

1. Navigate to the repository.
2. Search for an example Golang program.
3. Notice the absence of a "Hello World" example in Golang.

## Expected Behavior

A basic "Hello World" program in Golang should be added to the repository for users to get familiar with the language.

## Actual Behavior

Currently, there is no Golang example in the repository.

**Comment by aswathcm29** [comment]
It'd be great if you assign it to me under hacktoberfest

**Comment by handikatriarlan** [comment]
Thank you for raising this issue and your interest in contributing to the repository!

You're absolutely right; currently, there isn't a "Hello World" example in Golang, and adding one would be a great contribution to help beginners get familiar with the language.

If you're interested in adding this, feel free to submit a pull request (PR) following the contribution guidelines in our CONTRIBUTING.md. You can create a new folder under contributions/golang/ and add the hello_world.go file there.

**Comment by aswathcm29** [comment]
@handikatriarlan Thanks for assigning it ! I'll do it as per the contributing guidelines and raise the pull request asap

**Comment by handikatriarlan** [comment]
Okay!
