### ISSUE TITLE
feat : Adding Hello World program in malbolge

### ISSUE THREAD

**Issue by laxmanp090404** [handikatriarlan/hello-world-in-every-language#63]
This feature request proposes adding a "Hello, World!" program in **Malbolge**, an esoteric programming language known for its extreme difficulty and cryptic syntax. The purpose of this addition is to provide an example of a simple program in Malbolge for educational purposes and to showcase the language's complex nature.

#### Proposed Changes:
- Add a `hello_world.malbolge` file containing the following code:
  ```malbolge
  ('&%:9]!~}|z2Vxwv-,POqponl&%$#"!zyxwv-,POqponm
  ```

#### Reason for Adding:
- Malbolge is a rare and lesser-known language, and adding this example will introduce developers to the challenge of esoteric programming.
- The "Hello, World!" program will serve as a reference for those exploring obscure languages or testing their coding skills in unusual environments.

This feature will provide a fun and unique addition to the repository, broadening its range of programming language examples.

**Comment by handikatriarlan** [comment]
you need make a pr first. For detailed instructions on how to contribute, pls read [contribution guidelines](https://github.com/handikatriarlan/hello-world-in-every-language/blob/main/CONTRIBUTING.md)

**Comment by roshankraveendrababu** [comment]
@handikatriarlan  please assign me this issue . i will solve this diligently and quickly . this will help me in my professional devolopment. please consider this comment!!
