### ISSUE TITLE
 Adding Hello World in Rust

### ISSUE THREAD

**Issue by Aadhavancnp** [handikatriarlan/hello-world-in-every-language#7]
Adding the **rust** code for Hello World.

**Comment by Aadhavancnp** [comment]
@handikatriarlan , Please assign this issue to me under Hacktoberfest 2024.
Thanks!!

**Comment by handikatriarlan** [comment]
Sure, but you will need to submit a PR to this repository, see the [Contribution Guidelines](https://github.com/handikatriarlan/hello-world-in-every-language/blob/main/CONTRIBUTING.md) to find out how to do this.
